# -*- coding: utf-8 -*-
"""alpha-version.ipynb

Automatically generated by Colaboratory.
"""

# !pip install -U -q PyDrive

# from pydrive.auth import GoogleAuth
# from pydrive.drive import GoogleDrive
# from google.colab import auth
# from oauth2client.client import GoogleCredentials

# # 1. Authenticate and create the PyDrive client.
# auth.authenticate_user()
# gauth = GoogleAuth()
# gauth.credentials = GoogleCredentials.get_application_default()
# drive = GoogleDrive(gauth)

from skimage import color
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten,  InputLayer
from keras.layers import Conv2D, MaxPooling2D, ZeroPadding2D,  BatchNormalization,  UpSampling2D
from keras.optimizers import SGD,RMSprop,adam
from keras.utils import np_utils
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing.image import array_to_img, img_to_array, load_img
from keras import optimizers
import keras
from scipy.misc import imsave

downloaded = drive.CreateFile({'id':'IMAGE_ID'})
downloaded.GetContentFile('woman.jpg')

image = img_to_array(load_img('woman.jpg'))
image = np.array(image, dtype=float)

img = plt.imshow(image)

X = color.rgb2lab(1.0/255*image)[:,:,0]
Y = color.rgb2lab(1.0/255*image)[:,:,1:]

Y = Y/128

X = X.reshape(1,400,400,1)
Y = Y.reshape(1,400,400,2)

model = Sequential()

model.add(InputLayer(input_shape = (None,None,1)))
model.add(Conv2D(8,(3,3),activation='relu',padding='same',strides =2))
model.add(Conv2D(8,(3,3),activation='relu',padding='same'))
model.add(Conv2D(16,(3,3),activation='relu',padding='same'))
model.add(Conv2D(16,(3,3),activation='relu',padding='same',strides =2))
model.add(Conv2D(32,(3,3),activation='relu',padding='same'))
model.add(Conv2D(32,(3,3),activation='relu',padding='same',strides =2))
model.add(UpSampling2D((2,2)))
model.add(Conv2D(32,(3,3),activation='relu',padding='same'))
model.add(UpSampling2D((2,2)))
model.add(Conv2D(16,(3,3),activation='relu',padding='same'))
model.add(UpSampling2D((2,2)))
model.add(Conv2D(2,(3,3),activation='tanh',padding='same'))

model.compile(optimizer='rmsprop',loss='mse')

model.fit(x=X, y=Y, batch_size=1, epochs=100)

output = model.predict(X)

output = output * 128

canvas = np.zeros((400,400,3))

canvas[:,:,0] = X[0][:,:,0]

canvas[:,:,1:] = output[0]

canvas = color.lab2rgb(canvas)

imsave('my_image.png',color.lab2rgb(canvas))

file = drive.CreateFile({'parents':[{u'id': 'folder_id'}]})
file.SetContentFile('my_image.png')
file.Upload()